# Generated by Django 3.1.1 on 2020-11-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('react_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('authorImg', models.ImageField(upload_to='statics/img/customer')),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=9)),
                ('website', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('youtube', models.CharField(max_length=150)),
                ('img1', models.ImageField(upload_to='statics/img/customer')),
                ('img2', models.ImageField(upload_to='statics/img/customer')),
                ('img3', models.ImageField(upload_to='statics/img/customer')),
                ('img4', models.ImageField(upload_to='statics/img/customer')),
                ('img5', models.ImageField(upload_to='statics/img/customer')),
                ('img6', models.ImageField(upload_to='statics/img/customer')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text='Unique value for store page URL, created from name.', max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_match', to='core.categories')),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['pk'],
            },
        ),
    ]
