# Generated by Django 3.1.1 on 2020-12-14 00:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('icon_host', models.ImageField(blank=True, null=True, upload_to='storeMaster/icons')),
                ('slug', models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True)),
                ('react_icon', models.ImageField(blank=True, null=True, upload_to='storeMaster/banners')),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categoria de Tienda',
                'db_table': 'categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoriesProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('icon_host', models.ImageField(blank=True, null=True, upload_to='stores/categories')),
                ('slug', models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True)),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cate_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cateTop_match', to='core.categories')),
            ],
            options={
                'verbose_name_plural': 'Categoria de Producto',
                'db_table': 'catStores',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=55, null=True)),
                ('colors', models.CharField(blank=True, max_length=150, null=True)),
                ('sizes', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('img1host', models.ImageField(blank=True, null=True, upload_to='stores/productos')),
                ('img2host', models.ImageField(blank=True, null=True, upload_to='stores/productos')),
                ('img3host', models.ImageField(blank=True, null=True, upload_to='stores/productos')),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cate_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catego_match', to='core.categoriesprod')),
            ],
            options={
                'verbose_name_plural': 'Agregue un Proucto',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=300)),
                ('logo_host', models.ImageField(default='shorturl.at/bqsGJ', upload_to='stores/logos')),
                ('description', models.TextField(blank=True, null=True)),
                ('payments', models.CharField(blank=True, choices=[('EF', 'En Efectivo'), ('TC', 'Tarjeta de Credito o Debito'), ('TR', 'Transferencia Bancaria'), ('YP', 'Yape'), ('PL', 'Plim')], default='EF', max_length=2, null=True)),
                ('ruc', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phoneNum', models.CharField(blank=True, max_length=9, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=9, null=True)),
                ('img1host', models.ImageField(blank=True, null=True, upload_to='stores/banner')),
                ('img2host', models.ImageField(blank=True, null=True, upload_to='stores/banner')),
                ('img3host', models.ImageField(blank=True, null=True, upload_to='stores/banner')),
                ('img4host', models.ImageField(blank=True, null=True, upload_to='stores/banner')),
                ('img5host', models.ImageField(blank=True, null=True, upload_to='stores/banner')),
                ('img6host', models.ImageField(blank=True, null=True, upload_to='stores/banner')),
                ('video', models.CharField(blank=True, max_length=250, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text='Unique value for store page URL, created from name.', max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_match', to='core.categories')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tiendas',
                'db_table': 'stores',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_match', to='core.store')),
                ('point_prod', models.ManyToManyField(related_name='point_prod_match', to='core.ProductStore')),
            ],
            options={
                'verbose_name_plural': 'Ubicacion de Tienda',
            },
        ),
        migrations.AddField(
            model_name='productstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_match', to='core.store'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImg', models.ImageField(blank=True, null=True, upload_to='users/customers')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNum', models.CharField(blank=True, max_length=9, null=True)),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Informacion Usuarios',
            },
        ),
        migrations.AddField(
            model_name='categoriesprod',
            name='store_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeTop_match', to='core.store'),
        ),
    ]
