# Generated by Django 3.1.1 on 2020-11-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('icon_up', models.ImageField(blank=True, null=True, upload_to='img/categories')),
                ('icon_host', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True)),
                ('react_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CategoriesProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('icon_up', models.ImageField(blank=True, null=True, upload_to='img/categories')),
                ('icon_host', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Unique value for product page URL, created from name.', max_length=255, null=True, unique=True)),
                ('react_icon', models.CharField(blank=True, max_length=20, null=True)),
                ('activate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Category Product',
                'db_table': 'catStores',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, unique=True)),
                ('lastname', models.CharField(max_length=255, unique=True)),
                ('userImg', models.ImageField(blank=True, null=True, upload_to='img/categories')),
                ('userImgHost', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phoneNum', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True, help_text='True Moroso')),
                ('document', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True)),
                ('logo', models.ImageField(default='shorturl.at/bqsGJ', upload_to='img/stores')),
                ('logo_host', models.CharField(blank=True, max_length=350, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payments', models.CharField(blank=True, choices=[('EF', 'En Efectivo'), ('TC', 'Tarjeta de Credito o Debito'), ('TR', 'Transferencia Bancaria'), ('YP', 'Yape'), ('PL', 'Plim')], default='EF', max_length=2, null=True)),
                ('ruc', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNum', models.CharField(blank=True, max_length=9, null=True)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
                ('dni', models.CharField(blank=True, max_length=9, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=9, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img1host', models.CharField(blank=True, max_length=300, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img2host', models.CharField(blank=True, max_length=300, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img3host', models.CharField(blank=True, max_length=300, null=True)),
                ('img4', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img4host', models.CharField(blank=True, max_length=300, null=True)),
                ('img5', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img5host', models.CharField(blank=True, max_length=300, null=True)),
                ('img6', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img6host', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.CharField(blank=True, max_length=250, null=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('activate', models.BooleanField(default=True)),
                ('slug', models.SlugField(help_text='Unique value for store page URL, created from name.', max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_match', to='core.categories')),
            ],
            options={
                'verbose_name_plural': 'Stores',
                'db_table': 'stores',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img1host', models.CharField(blank=True, max_length=300, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img2host', models.CharField(blank=True, max_length=300, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('img3host', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cate_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catego_match', to='core.categoriesprod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_match', to='core.store', to_field='title')),
            ],
            options={
                'verbose_name_plural': 'Product Store',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
