# Generated by Django 3.1.1 on 2020-11-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstore',
            name='store',
            field=models.ForeignKey(default='get_default_store', on_delete=django.db.models.deletion.CASCADE, related_name='store_match', to='core.store'),
        ),
    ]
