# Generated by Django 3.1.1 on 2020-11-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201116_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='colors',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productstore',
            name='material',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='productstore',
            name='sizes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
